#!/bin/bash -e

DIR=test-install-dir
rm -rf $DIR/
virtualenv --distribute --system-site-packages $DIR
$DIR/bin/python setup.py install
LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH $DIR/bin/python -c "import infpy"

